export const books = [
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    publicationDate: '1925-04-10',
    country: 'USA',
    genre: 'Novel',
  },
  {
    title: '1984',
    author: 'George Orwell',
    publicationDate: '1949-06-08',
    country: 'UK',
    genre: 'Dystopian',
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publicationDate: '1813-01-28',
    country: 'UK',
    genre: 'Romance',
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    publicationDate: '1932-08-15',
    country: 'UK',
    genre: 'Dystopian',
  },
  {
    title: 'Moby Dick',
    author: 'Herman Melville',
    publicationDate: '1851-11-14',
    country: 'USA',
    genre: 'Adventure',
  },
  {
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    publicationDate: '1869-01-01',
    country: 'France',
    genre: 'Historical',
  },
  {
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    publicationDate: '1890-06-20',
    country: 'UK',
    genre: 'Novel',
  },
  {
    title: 'Les Misérables',
    author: 'Victor Hugo',
    publicationDate: '1862-01-01',
    country: 'France',
    genre: 'Historical',
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    publicationDate: '1951-07-16',
    country: 'USA',
    genre: 'Novel',
  },
  {
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    publicationDate: '1605-01-16',
    country: 'Spain',
    genre: 'Novel',
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    publicationDate: '1932-08-15',
    country: 'UK',
    genre: 'Dystopian',
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    publicationDate: '1960-07-11',
    country: 'USA',
    genre: 'Novel',
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    publicationDate: '1953-10-19',
    country: 'USA',
    genre: 'Dystopian',
  },
  {
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    publicationDate: '1877-01-01',
    country: 'France',
    genre: 'Novel',
  },
  {
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    publicationDate: '1880-01-01',
    country: 'Russia',
    genre: 'Novel',
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    publicationDate: '1937-09-21',
    country: 'UK',
    genre: 'Adventure',
  },
  {
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    publicationDate: '1847-12-01',
    country: 'UK',
    genre: 'Novel',
  },
  {
    title: 'The Road',
    author: 'Cormac McCarthy',
    publicationDate: '2006-09-26',
    country: 'USA',
    genre: 'Post-Apocalyptic',
  },
  {
    title: 'Slaughterhouse-Five',
    author: 'Kurt Vonnegut',
    publicationDate: '1969-03-31',
    country: 'USA',
    genre: 'Science Fiction',
  },
  {
    title: 'A Tale of Two Cities',
    author: 'Charles Dickens',
    publicationDate: '1859-04-30',
    country: 'UK',
    genre: 'Historical',
  },
  {
    title: 'Great Expectations',
    author: 'Charles Dickens',
    publicationDate: '1861-01-01',
    country: 'UK',
    genre: 'Novel',
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    publicationDate: '1847-10-16',
    country: 'UK',
    genre: 'Novel',
  },
  {
    title: 'The Sound and the Fury',
    author: 'William Faulkner',
    publicationDate: '1929-10-07',
    country: 'USA',
    genre: 'Modernist',
  },
  {
    title: 'The Old Man and the Sea',
    author: 'Ernest Hemingway',
    publicationDate: '1952-09-01',
    country: 'USA',
    genre: 'Novel',
  },
  {
    title: 'The Trial',
    author: 'Franz Kafka',
    publicationDate: '1925-04-26',
    country: 'Austria-Hungary',
    genre: 'Absurdist',
  },
  {
    title: 'The Bell Jar',
    author: 'Sylvia Plath',
    publicationDate: '1963-01-14',
    country: 'USA',
    genre: 'Novel',
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: 'Douglas Adams',
    publicationDate: '1979-10-12',
    country: 'UK',
    genre: 'Science Fiction',
  },
  {
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupéry',
    publicationDate: '1943-04-06',
    country: 'France',
    genre: 'Fable',
  },
  {
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    publicationDate: '1844-01-01',
    country: 'France',
    genre: 'Adventure',
  },
  {
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    publicationDate: '1939-04-14',
    country: 'USA',
    genre: 'Historical',
  },
  {
    title: 'The Road',
    author: 'Cormac McCarthy',
    publicationDate: '2006-09-26',
    country: 'USA',
    genre: 'Post-Apocalyptic',
  },
  {
    title: 'The Amazing Adventures of Kavalier & Clay',
    author: 'Michael Chabon',
    publicationDate: '2000-09-01',
    country: 'USA',
    genre: 'Historical',
  },
  {
    title: 'The Goldfinch',
    author: 'Donna Tartt',
    publicationDate: '2013-10-22',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'The Underground Railroad',
    author: 'Colson Whitehead',
    publicationDate: '2016-08-02',
    country: 'USA',
    genre: 'Historical',
  },
  {
    title: 'The Night Circus',
    author: 'Erin Morgenstern',
    publicationDate: '2011-09-13',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'Life of Pi',
    author: 'Yann Martel',
    publicationDate: '2001-09-11',
    country: 'Canada',
    genre: 'Adventure',
  },
  {
    title: 'The Fault in Our Stars',
    author: 'John Green',
    publicationDate: '2012-01-10',
    country: 'USA',
    genre: 'Contemporary',
  },
  {
    title: 'The Road',
    author: 'Cormac McCarthy',
    publicationDate: '2006-09-26',
    country: 'USA',
    genre: 'Post-Apocalyptic',
  },
  {
    title: 'The Brief Wondrous Life of Oscar Wao',
    author: 'Junot Díaz',
    publicationDate: '2007-09-11',
    country: 'USA',
    genre: 'Novel',
  },
  {
    title: 'The Amazing Adventures of Kavalier & Clay',
    author: 'Michael Chabon',
    publicationDate: '2000-09-01',
    country: 'USA',
    genre: 'Historical',
  },
  {
    title: 'The Book Thief',
    author: 'Markus Zusak',
    publicationDate: '2005-01-01',
    country: 'Australia',
    genre: 'Historical',
  },
  {
    title: 'The Lovely Bones',
    author: 'Alice Sebold',
    publicationDate: '2002-01-01',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'Atonement',
    author: 'Ian McEwan',
    publicationDate: '2001-09-01',
    country: 'UK',
    genre: 'Novel',
  },
  {
    title: 'Cloud Atlas',
    author: 'David Mitchell',
    publicationDate: '2004-01-01',
    country: 'UK',
    genre: 'Fiction',
  },
  {
    title: 'Room',
    author: 'Emma Donoghue',
    publicationDate: '2010-09-01',
    country: 'Ireland',
    genre: 'Fiction',
  },
  {
    title: 'Wild',
    author: 'Cheryl Strayed',
    publicationDate: '2012-03-20',
    country: 'USA',
    genre: 'Memoir',
  },
  {
    title: 'The Ocean at the End of the Lane',
    author: 'Neil Gaiman',
    publicationDate: '2013-06-18',
    country: 'UK',
    genre: 'Fiction',
  },
  {
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    publicationDate: '2018-08-14',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'A Man Called Ove',
    author: 'Fredrik Backman',
    publicationDate: '2012-12-30',
    country: 'Sweden',
    genre: 'Fiction',
  },
  {
    title: 'The Overstory',
    author: 'Richard Powers',
    publicationDate: '2018-04-03',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'Little Fires Everywhere',
    author: 'Celeste Ng',
    publicationDate: '2017-09-12',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'The Nightingale',
    author: 'Kristin Hannah',
    publicationDate: '2015-02-03',
    country: 'USA',
    genre: 'Historical Fiction',
  },
  {
    title: 'Before the Fall',
    author: 'Noah Hawley',
    publicationDate: '2016-05-31',
    country: 'USA',
    genre: 'Thriller',
  },
  {
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    publicationDate: '2019-02-05',
    country: 'UK',
    genre: 'Psychological Thriller',
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    publicationDate: '2018-02-20',
    country: 'USA',
    genre: 'Memoir',
  },
  {
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    publicationDate: '2005-08-01',
    country: 'Sweden',
    genre: 'Crime',
  },
  {
    title: 'The Light We Lost',
    author: 'Jill Santopolo',
    publicationDate: '2017-05-09',
    country: 'USA',
    genre: 'Contemporary Fiction',
  },
  {
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    publicationDate: '2003-05-29',
    country: 'Afghanistan',
    genre: 'Historical Fiction',
  },
  {
    title: 'The Girl on the Train',
    author: 'Paula Hawkins',
    publicationDate: '2015-01-13',
    country: 'UK',
    genre: 'Psychological Thriller',
  },
  {
    title: 'The Immortalists',
    author: 'Chloe Benjamin',
    publicationDate: '2018-01-09',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    publicationDate: '2017-06-13',
    country: 'USA',
    genre: 'Historical Fiction',
  },
  {
    title: 'Anxious People',
    author: 'Fredrik Backman',
    publicationDate: '2020-09-08',
    country: 'Sweden',
    genre: 'Fiction',
  },
  {
    title: 'Normal People',
    author: 'Sally Rooney',
    publicationDate: '2018-08-28',
    country: 'Ireland',
    genre: 'Contemporary Fiction',
  },
  {
    title: 'The Vanishing Half',
    author: 'Brit Bennett',
    publicationDate: '2020-06-02',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'The Goldfinch',
    author: 'Donna Tartt',
    publicationDate: '2013-10-22',
    country: 'USA',
    genre: 'Fiction',
  },
  {
    title: 'The Betrothed',
    author: 'Alessandro Manzoni',
    publicationDate: '1827-01-01',
    country: 'Italy',
    genre: 'Historical Fiction',
  },
  {
    title: 'The Leopard',
    author: 'Giuseppe Tomasi di Lampedusa',
    publicationDate: '1958-01-01',
    country: 'Italy',
    genre: 'Historical Fiction',
  },
  {
    title: 'Invisible Man',
    author: 'Ralph Ellison',
    publicationDate: '1952-01-01',
    country: 'Italy',
    genre: 'Novel',
  },
  {
    title: 'The Name of the Rose',
    author: 'Umberto Eco',
    publicationDate: '1980-01-01',
    country: 'Italy',
    genre: 'Historical Mystery',
  },
  {
    title: 'If on a Winter’s Night a Traveler',
    author: 'Italo Calvino',
    publicationDate: '1979-01-01',
    country: 'Italy',
    genre: 'Novel',
  },
];
